### ISSUE TITLE
how to inference yolov7 

### ISSUE THREAD

**Issue by knotgrass** [akashAD98/yolov7_custom_data_trainig#1]
I followed your instructions and it ran successfully.
Can you guide how to inference.
Thank you so much

**Comment by akashAD98** [comment]
@anh-viet-dang sure , ill update soon in readme file also

**Comment by akashAD98** [comment]
```python detect.py --weights yolov7.pt --conf 0.25 --img-size 640 --source inference/images/horses.jpg```

pass your custom mode weight & pass image/video in --source
