### ISSUE TITLE
Do I need to change the parameters in train.py?

### ISSUE THREAD

**Issue by zapplelove** [akashAD98/yolov7_custom_data_trainig#2]
When I read the code in [`train.py`](https://github.com/WongKinYiu/yolov7/blob/main/train.py), I find a code:
[`    hyp['cls'] *= nc / 80. * 3. / nl  # scale to classes and layers`](https://github.com/WongKinYiu/yolov7/blob/main/train.py#L283), and I don't understand what the 80 stands for. Is this the classes number of coco datasets?

**Comment by akashAD98** [comment]
@zapplelove your correct its number of clases, you can directly modify that in data.yaml file , you don't need to do change inside train.py . change this from .cfg & .yaml file

**Comment by zapplelove** [comment]
> @zapplelove your correct its number of clases, you can directly modify that in data.yaml file , you don't need to do change inside train.py . change this from .cfg & .yaml file

Actually, I don't understand what the `80` stands for instead of `nc`. I known If I modify the cfg & yaml, it can change `nc`, but why this line there is a num `80`.

**Comment by akashAD98** [comment]
@zapplelove i thik its by default coco 80 classes, but I'm not 100%sure, will be great if we ask this Q here https://github.com/WongKinYiu/yolov7/
