### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement requirements.txt

### ISSUE THREAD

**Issue by RonaldYuren** [akashAD98/yolov7_custom_data_trainig#3]
I just download the yolov7-zip file from github,  after I zipped it,  then paste it to my google drive.
I didn't success to run the code " !pip install requirements.txt"  on  google colab

what can i do to solve this problem?

**Comment by akashAD98** [comment]
@RonaldYuren  can you share the error log?
otherwise you can open this notebook in google collab & run 
https://github.com/akashAD98/yolov7_custom_data_trainig/blob/main/yolov7_custom_data_od.ipynb

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/184098802-e8d5572e-ebd9-40cd-a4cd-399567a8e029.png)


did I do anything wrong with my data?   Why it can't working on my custom dataset?

**Comment by akashAD98** [comment]
@RonaldYuren you are giving the wrong argument to train the model. use this or refrence
```python train.py --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights '' --name yolov7 --hyp data/hyp.scratch.p5.yaml```

**Comment by RonaldYuren** [comment]
> @akashAD98 

![image](https://user-images.githubusercontent.com/95292013/184101407-e47c8ff9-1446-41f9-8b04-981c633508d8.png)


I think the " img 640 640"   so I change to my images' size,   but it came another problem...

**Comment by akashAD98** [comment]
@RonaldYuren your not using cuda, click on runtime & select device -gpu
<img width="314" alt="image" src="https://user-images.githubusercontent.com/62583018/184102169-56f6c909-d70a-44a8-9644-9e71184c14eb.png">


& check ```nvidia-smi``` for which GPU you got

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/184103349-31c87b64-a484-4e8c-85cd-f857c20ac1d2.png)


there is something wrong but I am a deeplearning rookie,  some doesn't set up right?

**Comment by akashAD98** [comment]
@RonaldYuren  can you try ```!pip install PyYAML==5.4.1``` &restart executing all notebook again..

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/184132739-6b3b1cff-2bcb-483c-8841-8a4d1e629e1b.png)


did I make wrong on my data?      I use opencv to grab infomation about a moving 2D-rectangle from several frames

**Comment by akashAD98** [comment]
yes your not passing correct path or your missing labels, please check my readme ,I have attached screenshot of customdata folder

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/184312647-91d5801a-957c-48ce-8746-0c0145613788.png)
![image](https://user-images.githubusercontent.com/95292013/184312734-3141e52e-943a-4790-acbc-5199158772e4.png)


it shows that no labels detected in my train.cache ,    but there are only images' path in a " train.txt"  right??
I have create "labels" folder  with another images folder,    Do I need to mark these labels' path in somewhere??

**Comment by RonaldYuren** [comment]
Do you find any problem?   I am not sure where to add labels' path

because train.txt and valid.txt  only have the images' path；what about labels' path?

**Comment by akashAD98** [comment]
you can create folder customdata
inside that images-(all images of train/val) & labels(train/val)

outside customdatafolde create train.txt & val.txt
& inside train.txt
it should be  like this 
(don't pass all path )

<img width="272" alt="image" src="https://user-images.githubusercontent.com/62583018/184916320-2c679d62-4bb2-4c49-a028-7624cda8ab74.png">

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/184926970-5f529f83-e1d5-44a6-8d0d-82df1927d1f1.png)

I solve the question by arrange the folders' position
But what the step7 will show??         I'm not sure to add what file's path for it    
I got some error when I put a photo(random from my valid folder) , the error will paste below.

![image](https://user-images.githubusercontent.com/95292013/185021117-1dc96555-c386-4f4d-b2e8-0855bfe3d370.png)

![image](https://user-images.githubusercontent.com/95292013/184927515-f3b330d6-659c-438e-af45-99b9904342c7.png)

**Comment by RonaldYuren** [comment]
I think the step7 is to detect and visualize right?  But I haven't solved the RuntimeError I paste

**Comment by RonaldYuren** [comment]
![image](https://user-images.githubusercontent.com/95292013/185103665-7c11f9c5-ec15-48bc-9cb7-79863fb89e89.png)

does this fail on COLAB ?

**Comment by akashAD98** [comment]
@RonaldYuren collab is not supporting inferencing.you can save video & check detections

**Comment by RonaldYuren** [comment]
@akashAD98 

does colab can get detection and video from the detect.py  (in step7) ?
or How the detect.py work colab?    do I need to change some of the item in step 7
![image](https://user-images.githubusercontent.com/95292013/185107808-63f21eeb-90c2-45f6-98d9-052beb4705a1.png)

**Comment by akashAD98** [comment]
yes try it , results will saved in runs

**Comment by RonaldYuren** [comment]
@akashAD98 

![image](https://user-images.githubusercontent.com/95292013/185113174-c0ef094a-c15d-48dc-9a22-9717206e8450.png)

I have some problem with the following command
!python detect.py --weights yolov7.pt --conf 0.25 --img-size 972 --source inference/images/test1.jpg

**Comment by RonaldYuren** [comment]
@akashAD98      I am using the rectangle(moving on my grid map)   to do object-detection
![image](https://user-images.githubusercontent.com/95292013/185151032-54e22300-1840-4f59-afe5-967b4416d306.png)


and the following picture is outcome after *train.py*    ,May I ask you  how to explain this picture?
![image](https://user-images.githubusercontent.com/95292013/185151837-d3337688-b369-4510-a466-e33b43500704.png)




By the way , I still can't deal with the error from detect.py  I mentioned above.....
![image](https://user-images.githubusercontent.com/95292013/185152078-4c9eda7c-22de-449f-b210-bd4befcffa34.png)

**Comment by RonaldYuren** [comment]
@akashAD98 

I found problem with my detect.py,   My test image is 972*972, while in training ,train.py resize it to 992*992 (multiple for 32)
the 

> @akashAD98 I am using the rectangle(moving on my grid map) to do object-detection ![image](https://user-images.githubusercontent.com/95292013/185151032-54e22300-1840-4f59-afe5-967b4416d306.png)
> 
> and the following picture is outcome after _train.py_ ,May I ask you how to explain this picture? ![image](https://user-images.githubusercontent.com/95292013/185151837-d3337688-b369-4510-a466-e33b43500704.png)
> 
> By the way , I still can't deal with the error from detect.py I mentioned above..... ![image](https://user-images.githubusercontent.com/95292013/185152078-4c9eda7c-22de-449f-b210-bd4befcffa34.png)




@akashAD98 

I found problem with my detect.py,   My test image is 972*972, while in training ,train.py resize it to 992*992 (multiple for 32)
the next I will try to use my  video
But!!!!!   I am not sure how to explain the train_batch4.jpg I mentioned before

**Comment by RonaldYuren** [comment]
@akashAD98 

Hi, Does yolo can predict the object's length and width through training?
Are there any source can deal with this question?

**Comment by akashAD98** [comment]
@RonaldYuren object length means width & height of detected object?

**Comment by RonaldYuren** [comment]
> @RonaldYuren object length means width & height of detected object?

Yes!

@akashAD98 
Can I ask about this picture,  I want to use image name defined by myself, How to do this? how to modify ?
![image](https://user-images.githubusercontent.com/95292013/186116796-fb19f3bf-2763-4fe7-85a4-575e193276bf.png)

**Comment by akashAD98** [comment]
@RonaldYuren automatically your named image file output will be saved in runs

**Comment by RonaldYuren** [comment]
@akashAD98 
May I ask this question about this picture, I have labeled this image by OpenCV, but its bounding box is large, there is big part of dark space in the box, does the black space will influence the performance in my training?

I have create different green rectangles with length( >200m : large ship ；100~200m: medium ship )
But I am confused that this bounding box can explain the difference about length?


![image](https://user-images.githubusercontent.com/95292013/186607153-33f009c5-d63c-4c82-853b-6efbfac8b2db.png)






it didn't draw the bounding box for my test image, Why? did I choose the the wrong training process? 
( batch_size = 2, due to the RAM for colab, I need to decrease the size,  and epochs=50)
![image](https://user-images.githubusercontent.com/95292013/186837401-bf04ddcc-a4e8-45bc-850c-ce6db195b91c.png)

**Comment by RonaldYuren** [comment]
@akashAD98 
I think this might be a similar situation like "YOLOv5 oriented bounding box"
Does v7 can deal with this question?

**Comment by akashAD98** [comment]
@RonaldYuren what data exactly its?  not able to understand what exactly your detecting? can you give more info about your model data etc.  maybe you need to do training for more epochs, also how many no training samples are there

**Comment by RonaldYuren** [comment]
@akashAD98 
I write down the question, I use different color to mark the step and my question


![image](https://user-images.githubusercontent.com/95292013/186946205-5eb3b4c4-babe-491a-a6c4-b7e59b67f447.png)

**Comment by akashAD98** [comment]
@RonaldYuren yes it will detect things, also you can check semantic segmention for doing the same task. it will do pixel by pixel classification

**Comment by RonaldYuren** [comment]
> @RonaldYuren yes it will detect things, also you can check semantic segmention for doing the same task. it will do pixel by pixel classification

@akashAD98     Does it means that YOLOv7 model will accept my " Yellow bounding box"  format (X , Y, W_yellow, H_yellow) ?

**Comment by akashAD98** [comment]
yes . you can do small experiment

**Comment by RonaldYuren** [comment]
> yes . you can do small experiment

@akashAD98   Thx very much!!  I will try to do such experiment, I hope it would work, because that there is seldom model dealing with the problem about " bbox's angle"

**Comment by RonaldYuren** [comment]
@akashAD98 
Can I just use this code on our school's ubuntu server? 
Does any step I need to be careful?


I found that I can't download the gputil  because of my pip version(22.1)?

**Comment by akashAD98** [comment]
@RonaldYuren you can use this code

**Comment by RonaldYuren** [comment]
@akashAD98 
I want to ask if I use " picture only with one rectangle "   to training,
YOLOv7 couldn't detect " pictures with several rectangles "  ?    or I only need to train for a big amount of  "one-rectangle picture"

**Comment by akashAD98** [comment]
@RonaldYuren i haven't tried it ,you can ask same q in official repo
